### ISSUE TITLE
How to load a 'wild' firmware into Angr

### ISSUE THREAD

**Issue by chubbymaggie** [angr/angr#23]
I am trying to load a firmware into Angr for which I know neither the entry point nor the architecture in which it runs (hence, 'wild') IDA pro too fails to determine those details automatically.

When I try these two options: 
`
proj = angr.Project("wild_firmware.bin", load_options={ 'auto_load_libs': False})
`
OR
`
proj = angr.Project("wild_firmware.bin", load_options={'main_opts': {'backend': 'blob'}, 'auto_load_libs': False})
`
I am getting this error:
`
cle.errors.CLEError: All backends failed loading /home/xyz/angr/firmware/wild_firmware.bin!
`

But, when I try to guess the architecture,
`proj = angr.Project("wild_firmware.bin", load_options={'main_opts': {'backend': 'blob', 'custom_arch': 'ARM'}, 'auto_load_libs': False})`

I am getting this error:
`AttributeError: 'Blob' object has no attribute 'is_ppc64_abiv1'`

What is the best way to identify entry_point/architecture of a 'wild' firmware using Angr

Thanks

**Comment by rhelmot** [comment]
That's a bug. I'll take care of that.

**Comment by ltfish** [comment]
By the way, `angr.analyses.Boyscout` can try to guess the architecture and endianness of a blob.

**Comment by rhelmot** [comment]
heyyyyyy @ltfish you should _totally_ write about that in the docs, wink wink nudge nudge!

**Comment by ltfish** [comment]
Oh, I need more free time to do that.

And what's more, `angr.analyses.Girlscout` can try to guess the base address of a blob... no documentation as well :-(

**Comment by rhelmot** [comment]
Fixed in 6839e900

**Comment by chubbymaggie** [comment]
@rhelmot Thank you for the quick fix. However, I still have the issue.
If I load the image using following code:
`proj = angr.Project("wild_firmware.bin", load_options={'main_opts': {'backend': 'blob'}, 'auto_load_libs': False})`
I still get the error:
` cle.errors.CLEError: All backends failed loading /home/xyz/angr/firmware/wild_firmware.bin!`

However, if I wildly guess the architecture, it works. For example, this loads the image without any error: 
`proj = angr.Project("wild_firmware.bin", load_options={'main_opts': {'backend': 'blob', 'custom_arch': 'ARM'}, 'auto_load_libs': False})`

and I use `BoyScout` to determine the architecture (`bs = proj.analyses.BoyScout()`). In my case, it is returning `X86` which may be true (I am not sure though)

Is it necessary to set  `custom_arch` parameter for `blob` or its a bug? I thought, we can simply load the image and then use  `BoyScout` to determine the architecture.

**Comment by chubbymaggie** [comment]
Further, `proj.analyses.GirlScout()` giving  this error:

`ValueError: Pulling C data out of a non-root Clemory is disallowed!`
