### ISSUE TITLE
CFGEmulated created failed

### ISSUE THREAD

**Issue by Icegrave0391** [angr/angr#2580]
Hi, I tried to use CFGEmulated  to recover the cfg of binary wget :
```
p = angr.Project("/usr/bin/wget", load_options={"auto_load_libs": False})
ecfg = p.analyses.CFGEmulated(starts=[p.entry], keep_state=True)
```
However, I got the error message
```
ERROR   | 2021-03-28 20:57:17,687 | angr.state_plugins.posix | Trying to close a symbolic file descriptor
Traceback (most recent call last):
...
File "path/venv/lib/python3.7/site-packages/claripy/ast/base.py", line 1006, in __getattr__
    raise AttributeError(a)
AttributeError: to_claripy
```
Seems that a symbol fd handling error occurred?

**Comment by rhelmot** [comment]
I've pushed a change which attempts to address this problem. Can you try again with the latest angr installed via the angr-dev repository?

**Comment by silviasfon** [comment]
I just updated my repository and I'm still getting this same error

**Comment by rhelmot** [comment]
Please open a new issue with precise reproduction instructions.
