### ISSUE TITLE
fail to creating CFG using angr=9.2.40 

### ISSUE THREAD

**Issue by abduqasem** [angr/angr#3838]
### Description

Hello,
Last night, I tried angr==9.2.40 to analyze a MIPS binary file with the following code:
```py
project = angr.Project(binaryFileName, auto_load_libs=False)
cfg = project.analyses.CFG(resolve_indirect_jumps=True, cross_references=True, force_complete_scan=False,normalize=True, symbols=True, data_references=True)
```
creating cfg, create the following error attached in the image.
It is worth mentioning that angr==9.2.26 successfully create cfg.

Regarding the binary file, I emailed fish by email when I asked about another issue last time.

Regards,
![image](https://user-images.githubusercontent.com/47875913/222549154-d0fd4390-c0fb-4b24-936b-84e1a9fc6151.png)

**Comment by ltfish** [comment]
Can I have the binary to reproduce this issue? I know how to fix it, but I’d like to confirm the fix before pushing the fix.

**Comment by abduqasem** [comment]
I sent it to you by email a minute ago.

**Comment by ltfish** [comment]
Thanks for reporting. This issue has been fixed with PR #3853. PR #3856 will reduce the CFG recovery time on this binary to less than three and half minutes.

**Comment by abduqasem** [comment]
I have installed the latest angr version 9.2.41, and I tested over the binary I provided earlier. Unfortunately,  the issue has not been solved yet. I still have the same crashing error, when I create cfg.

**Comment by abduqasem** [comment]
Hello,
I checked it again after you pushed the new commit into the master version, and the issue still exists.
It fails to create cfg, with the same error I mentioned in the attached image earlier.

Please, when you have time, check the sample I attached to this issue.

**Comment by rhelmot** [comment]
Can you please post your `python -m angr.misc.bug_report` to verify you're on the right version?

**Comment by abduqasem** [comment]
/home/jovyan/angr-dev/angr/angr/misc/bug_report.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
angr environment report
=============================
Date: 2023-03-14 02:49:53.029783
Running in virtual environment at /home/jovyan/.virtualenvs/angr42
Platform: linux-x86_64
Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0]
######## angr #########
Python could not find angr
######## ailment #########
Python could not find ailment
######## cle #########
Python could not find cle
######## pyvex #########
Python could not find pyvex
######## claripy #########
Python could not find claripy
######## archinfo #########
Python could not find archinfo
######## z3 #########
Python found it in /home/jovyan/.virtualenvs/angr42/lib/python3.8/site-packages/z3
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /home/jovyan/.virtualenvs/angr42/lib/python3.8/site-packages/unicorn
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/jovyan/angr-dev/angr/angr/state_plugins/../lib/angr_native.so', handle 22c1e50 at 0x7ff929ddafd0>
unicorn: <CDLL '/home/jovyan/.virtualenvs/angr42/lib/python3.8/site-packages/unicorn/lib/libunicorn.so.2', handle 1c126c0 at 0x7ff930e29490>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7ff9303d39a0>
z3: <CDLL '/home/jovyan/.virtualenvs/angr42/lib/python3.8/site-packages/z3/lib/libz3.so', handle 1f8f070 at 0x7ff92bce69d0>

**Comment by rhelmot** [comment]
...I see. bug_report is broken. Can you please post your `python -c "print(__import__('angr').__version__)"`?

**Comment by abduqasem** [comment]
AttributeError: module 'angr' has no attribute '__version__'

but with angr 9.2.24, it works

**Comment by rhelmot** [comment]
https://github.com/angr/angr/blob/master/angr/__init__.py#L4

You are definitely doing something wrong.

**Comment by abduqasem** [comment]
I use the following command to install the latest updates.

git clone https://github.com/angr/angr-dev
cd angr-dev
./setup.sh -i -e angr

**Comment by rhelmot** [comment]
Are you running your python shell in the angr-dev folder? python will interpret the angr repository (NOT the angr package) as a namespace package that will be returned when you type `import angr`.

**Comment by abduqasem** [comment]
After I used the following commands :
pip install angr --upgarde


/home/jovyan/.virtualenvs/angr43/lib/python3.8/site-packages/angr/misc/bug_report.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
angr environment report
=============================
Date: 2023-03-14 03:15:58.846938
Running in virtual environment at /home/jovyan/.virtualenvs/angr43
Platform: linux-x86_64
Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0]
######## angr #########
Python found it in /home/jovyan/.virtualenvs/angr43/lib/python3.8/site-packages/angr
Pip version angr 9.2.41
Couldn't find git info
######## ailment #########
Python found it in /home/jovyan/.virtualenvs/angr43/lib/python3.8/site-packages/ailment
Pip version ailment 9.2.41
Couldn't find git info
######## cle #########
Python found it in /home/jovyan/.virtualenvs/angr43/lib/python3.8/site-packages/cle
Pip version cle 9.2.41
Couldn't find git info
######## pyvex #########
Python found it in /home/jovyan/.virtualenvs/angr43/lib/python3.8/site-packages/pyvex
Pip version pyvex 9.2.41
Couldn't find git info
######## claripy #########
Python found it in /home/jovyan/.virtualenvs/angr43/lib/python3.8/site-packages/claripy
Pip version claripy 9.2.41
Couldn't find git info
######## archinfo #########
Python found it in /home/jovyan/.virtualenvs/angr43/lib/python3.8/site-packages/archinfo
Pip version archinfo 9.2.41
Couldn't find git info
######## z3 #########
Python found it in /home/jovyan/.virtualenvs/angr43/lib/python3.8/site-packages/z3
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /home/jovyan/.virtualenvs/angr43/lib/python3.8/site-packages/unicorn
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/jovyan/.virtualenvs/angr43/lib/python3.8/site-packages/angr/state_plugins/../lib/angr_native.so', handle 2474550 at 0x7f8a4f650340>
unicorn: <CDLL '/home/jovyan/.virtualenvs/angr43/lib/python3.8/site-packages/unicorn/lib/libunicorn.so.2', handle 1dc3230 at 0x7f8a567135b0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f8a55c7cac0>
z3: <CDLL '/home/jovyan/.virtualenvs/angr43/lib/python3.8/site-packages/z3/lib/libz3.so', handle 213fcc0 at 0x7f8a515b5af0>

**Comment by abduqasem** [comment]
you are right,
'9.2.42.dev0' 
Thank you for your patience. The issue is solved.
when I use git clone https://github.com/angr/angr-dev
it does not overwrite the old angr-dev. when I installed it in a new directory. It works.
Thank you

**Comment by ltfish** [comment]
FYI #3858 will speed up CFG for your binary even more.
