### ISSUE TITLE
angr fails to generate cfg 

### ISSUE THREAD

**Issue by abduqasem** [angr/angr#3971]
### Description

When I use angr to create cfg, it crashes with following error. The  crash is generated over 9.2.44 and 9.2.50

 ```
cfg = project.analyses.CFG(resolve_indirect_jumps=True, cross_references=True,
      2                                            force_complete_scan=False,
      3                                                                                       normalize=True, symbols=True, data_references=True)

File ~/angr49/angr-dev/angr/angr/analyses/analysis.py:216, in AnalysisFactory.__call__(self, *args, **kwargs)
    210 show_progressbar = kwargs.pop("show_progressbar", False)
    212 w = self.prep(
    213     fail_fast=fail_fast, kb=kb, progress_callback=progress_callback, show_progressbar=show_progressbar
    214 )
--> 216 r = w(*args, **kwargs)
    217 # clean up so that it's always pickleable
    218 r._progressbar = None

File ~/angr49/angr-dev/angr/angr/analyses/analysis.py:201, in AnalysisFactory.prep.<locals>.wrapper(*args, **kwargs)
    198 oself._progress_callback = progress_callback
    200 oself._show_progressbar = show_progressbar
--> 201 oself.__init__(*args, **kwargs)
    202 return oself

File ~/angr49/angr-dev/angr/angr/analyses/cfg/cfg.py:68, in CFG.__init__(self, **kwargs)
     65         raise OutdatedError(outdated_exception)
     67 # Now initializes CFGFast :-)
---> 68 CFGFast.__init__(self, **kwargs)

File ~/angr49/angr-dev/angr/angr/analyses/cfg/cfg_fast.py:841, in CFGFast.__init__(self, binary, objects, regions, pickle_intermediate_results, symbols, function_prologues, resolve_indirect_jumps, force_segment, force_smart_scan, force_complete_scan, indirect_jump_target_limit, data_references, cross_references, normalize, start_at_entry, function_starts, extra_memory_regions, data_type_guessing_handlers, arch_options, indirect_jump_resolvers, base_state, exclude_sparse_regions, skip_specific_regions, heuristic_plt_resolving, detect_tail_calls, low_priority, cfb, model, use_patches, elf_eh_frame, exceptions, skip_unmapped_addrs, nodecode_window_size, nodecode_threshold, nodecode_step, indirect_calls_always_return, jumptable_resolver_resolves_calls, start, end, collect_data_references, extra_cross_references, **extra_arch_options)
    832 self._decoding_assumption_relations = None
    834 # A mapping between address and the actual data in memory
    835 # self._memory_data = { }
    836 # A mapping between address of the instruction that's referencing the memory data and the memory data itself
   (...)
    839
    840 # Start working!
--> 841 self._analyze()

File ~/angr49/angr-dev/angr/angr/analyses/forward_analysis/forward_analysis.py:247, in ForwardAnalysis._analyze(self)
    240 self._pre_analysis()
    242 if self._graph_visitor is None:
    243     # There is no base graph that we can rely on. The analysis itself should generate successors for the
    244     # current job.
    245     # An example is the CFG recovery.
--> 247     self._analysis_core_baremetal()
    249 else:
    250     # We have a base graph to follow. Just handle the current job.
    252     self._analysis_core_graph()

File ~/angr49/angr-dev/angr/angr/analyses/forward_analysis/forward_analysis.py:391, in ForwardAnalysis._analysis_core_baremetal(self)
    387 self._job_map.pop(self._job_key(job_info.job), None)
    389 self._job_info_queue = self._job_info_queue[1:]
--> 391 self._process_job_and_get_successors(job_info)
    393 # Short-cut for aborting the analysis
    394 if self.should_abort:

File ~/angr49/angr-dev/angr/angr/analyses/forward_analysis/forward_analysis.py:409, in ForwardAnalysis._process_job_and_get_successors(self, job_info)
    400 """
    401 Process a job, get all successors of this job, and call _handle_successor() to handle each successor.
    402
    403 :param JobInfo job_info: The JobInfo instance
    404 :return: None
    405 """
    407 job = job_info.job
--> 409 successors = self._get_successors(job)
    411 all_new_jobs = []
    413 for successor in successors:

File ~/angr49/angr-dev/angr/angr/analyses/cfg/cfg_fast.py:1294, in CFGFast._get_successors(self, job)
   1285 def _get_successors(self, job: CFGJob) -> List[CFGJob]:  # type: ignore[override] # pylint:disable=arguments-differ
   1286     # current_function_addr = job.func_addr
   1287     # addr = job.addr
   (...)
   1291     # else:
   1292     #    l.debug("Tracing new exit %#x", addr)
-> 1294     jobs = self._scan_block(job)
   1296     # l.debug("... got %d jobs: %s", len(jobs), jobs)
   1298     job_: CFGJob

File ~/angr49/angr-dev/angr/angr/analyses/cfg/cfg_fast.py:1668, in CFGFast._scan_block(self, cfg_job)
   1665     entries = self._scan_procedure(cfg_job, current_func_addr)
   1667 else:
-> 1668     entries = self._scan_irsb(cfg_job, current_func_addr)
   1670 return entries

File ~/angr49/angr-dev/angr/angr/analyses/cfg/cfg_fast.py:1862, in CFGFast._scan_irsb(self, cfg_job, current_func_addr)
   1860 # Scan the basic block to collect data references
   1861 if self._collect_data_ref:
-> 1862     self._collect_data_references(irsb, addr)
   1864 # Get all possible successors
   1865 irsb_next, jumpkind = irsb.next, irsb.jumpkind

File ~/angr49/angr-dev/angr/angr/analyses/cfg/cfg_fast.py:2423, in CFGFast._collect_data_references(self, irsb, irsb_addr)
   2413 def _collect_data_references(self, irsb, irsb_addr):
   2414     """
   2415     Unoptimizes IRSB and _add_data_reference's for individual statements or
   2416     for parts of statements (e.g. Store)
   (...)
   2420     :return: None
   2421     """
-> 2423     if irsb.data_refs:
   2424         self._process_irsb_data_refs(irsb)
   2425     elif irsb.statements:
   2426         # for each statement, collect all constants that are referenced or used.

AttributeError: 'NoneType' object has no attribute 'data_refs'
```

### Steps to reproduce the bug

```
project = angr.Project(binaryFileName, auto_load_libs=False,  use_sim_procedures=True, default_analysis_mode='symbolic',load_options={'auto_load_libs': False})
r_ =  project.analyses.CompleteCallingConventions(recover_variables=True, analyze_callsites=True)
cfg = project.analyses.CFG(resolve_indirect_jumps=True, cross_references=True,
                                           force_complete_scan=False,
                                           normalize=True, symbols=True, data_references=True)


```
[92254_httpd.zip](https://github.com/angr/angr/files/11527173/92254_httpd.zip)

**Comment by ltfish** [comment]
This is a bug that I just fixed on a separate branch. It *should* go away once https://github.com/angr/angr/pull/3966 is merged.

**Comment by abduqasem** [comment]
I have installed the latest version 9.2.52.dev0, and the problem still exists. I have attached the sample earlier, please check when you have time.
