### ISSUE TITLE
CFGFast (branch: fix/returning_checks) function returning wrongly calculated

### ISSUE THREAD

**Issue by axt** [angr/angr#420]
Note: this only affects fix/returning_checks branch, master is not affected!

I'm using this sample: https://github.com/axt/angr-utils/blob/master/examples/samples/1.6.26-libjsound.so, and this function: `HAE_Allocate` (0x29e50).

Starting with this commit https://github.com/angr/angr/commit/16ed8f, the indirect jumps in the PLT is not resolved correctly:

![cfgfst](https://cloud.githubusercontent.com/assets/759365/24829500/3935100e-1c73-11e7-9244-7734e441faa2.png)

It seems to me that the jumpout site is only added in `make_functions` but before that happens, `_analyze_function_features` already decides that the function doesn't return.

@ltfish Can you have a look at this?

**Comment by ltfish** [comment]
I think this bug has been found in testing and is fixed before I merge things to master. Can you please test it again?

**Comment by axt** [comment]
I dont have access to my laptop at the moment. I can test it tomorrow evening (~30 hours from now). Will test the other issue (return edges) too.

**Comment by axt** [comment]
After branch merge:

CFG recovery doesn't stop at `UnresolvableTarget`, but SimProcedures still not recognized. (One is memalign, which is hooked with `ReturnUnconstrained` by the loader, the other is `memset` which is hooked with `memset` by the loader.)

![cfgfst_asm](https://cloud.githubusercontent.com/assets/759365/25096445/87a85fd2-23a0-11e7-9ce0-ef3e6f8e3a60.png)

**Comment by axt** [comment]
Seems fixed on branch, thanks!

**Comment by axt** [comment]
Sidenote: 

Several commits ago, if I specified:
```python
project.analyses.CFGFast(
  symbols=False, 
  function_prologues=False, 
  force_complete_scan=False, 
  function_starts = [addr]
)
```
then I only got the function at `addr`, and all of its called functions in the CFG/kb. Since (not sure) `fix/function_returning_checks`, I always get an extra function (`call_gmon_start` in this case). 

I wouldn't consider it as a bug, but maybe its an indication of an off-by-one error.

**Comment by ltfish** [comment]
@axt what you described is the intended behavior. `function_starts` is used as _extra_ starts besides the start points that `CFGFast` gets, which always include the entry point of the project. As there is no easy way to prevent CFGFast from using the entry point as one of the start points, I just added a new option `start_at_entry`. If you specify `start_at_entry` to False, you will get the expected behavior (CFGFast will only start scanning at `addr`).

**Comment by ltfish** [comment]
Here is the new commit: 20377f6f50e6d5b7fa3f1e7a93f0ff661fe4380c

**Comment by ltfish** [comment]
The branch is merged to master. I'm closing this issue.
