### ISSUE TITLE
Branch not detected on ARM binary

### ISSUE THREAD

**Issue by tyb0807** [angr/angr#514]
Hello,

A picture is worth a thousand words...

![issue](https://user-images.githubusercontent.com/23738463/27800919-cc2b521a-601b-11e7-9ce3-3dd1d67f5a7a.png)

As you can see, block at 0x10445 has 3 out edges... Apparently, `cbz` instruction is not considered as a branch... Do you have any ideas on what's going on, or tell me how to fix this please?

Thank you in advance

**Comment by ltfish** [comment]
Can you turn off IR optimization and try it again?

**Comment by tyb0807** [comment]
Yes I've tried to pass `iropt_level=0` to it but nothing has changed... We still got 3 edges

**Comment by tyb0807** [comment]
Here's what I got with `Project.factory.block(0x10445).vex.pp()`

```
   00 | ------ IMark(0x10444, 2, 1) ------
   01 | PUT(itstate) = 0x00000000
   02 | t24 = GET:I32(r2)
   03 | t23 = CmpEQ32(t24,0x00000000)
   04 | if (t23) { PUT(ip) = 0x10473; Ijk_Boring }
   05 | PUT(ip) = 0x00010447
   06 | ------ IMark(0x10446, 2, 1) ------
   07 | t26 = GET:I32(r1)
   08 | t56 = LDle:I8(t26)
   09 | t58 = 8Uto32(t56)
   10 | PUT(r3) = t58
   11 | PUT(ip) = 0x00010449
   12 | ------ IMark(0x10448, 2, 1) ------
   13 | t32 = GET:I32(r13)
   14 | t31 = Sub32(t32,0x00000004)
   15 | PUT(r13) = t31
   16 | t9 = And32(t31,0xfffffffc)
   17 | t34 = GET:I32(r4)
   18 | STle(t9) = t34
   19 | PUT(ip) = 0x0001044b
   20 | ------ IMark(0x1044a, 2, 1) ------
   21 | t36 = GET:I32(r0)
   22 | t57 = LDle:I8(t36)
   23 | t59 = 8Uto32(t57)
   24 | PUT(r4) = t59
   25 | ------ IMark(0x1044c, 2, 1) ------
   26 | PUT(cc_op) = 0x00000002
   27 | PUT(cc_dep1) = t59
   28 | PUT(cc_dep2) = t58
   29 | PUT(cc_ndep) = 0x00000000
   30 | PUT(ip) = 0x0001044f
   31 | ------ IMark(0x1044e, 2, 1) ------
   32 | PUT(itstate) = 0x00000000
   33 | t61 = CmpNE32(t59,t58)
   34 | t60 = 1Uto32(t61)
   35 | t62 = 32to1(t60)
   36 | if (t62) { PUT(ip) = 0x1046d; Ijk_Boring }
   NEXT: PUT(pc) = 0x00010451; Ijk_Boring
```
I see that statement 4 indicates indeed a conditional branch. But the CFG is still not correct. Can you suggest me anything to debug this please?

**Comment by rhelmot** [comment]
Can you explain why this is actually an issue? Basic blocks are allowed to have several exits; this is totally legal in vex terms, and the IR and CFG are both correct the way I see it.

@ltfish we were both talking with Lukas yesterday about different situations where this would happen, so it seems like it would absolutely be not something we need fixed, is it?

**Comment by tyb0807** [comment]
Well, intuitively I would say cbz is also a branch instruction, so it's supposed to terminate a basic block. But yeah I forget about how iRSB is different from a basic block definition from Wikipedia. So I don't really know what should be the correct behavior in this case?

**Comment by tyb0807** [comment]
If this is not a bug, then I'm closing this. Thanks guys

**Comment by ltfish** [comment]
While I agree that IRSBs can have multiple exits located at different instructions, it does make performing analysis more annoying. Most people (especially when they are writing static analysis routines) want to work with basic blocks instead of super blocks. We _may_ want to make IRSB behave more like basic blocks.

**Comment by ltfish** [comment]
I feel more discussions are required. Hence, I reopened the issue.

**Comment by rhelmot** [comment]
I would gladly take the pull request if you were to hide it behind an option in the vex arguments. If you look through the commit history you'll see there's this one struct of "weird optional arguments we want to be able to modify each lift" and contains things like the maximum number of instructions per block and how to optimize thumb instruction conditionals. The task is to add an option for "strict basic block ends" or something and use it to control whether the code you added in that patch will actually execute. This will ensure we'll be able to upstream it successfully.

**Comment by ArtemShypotilov** [comment]
Hi Guys!

I have also ran into this issue recently. It is very important for me to fix this. 
I often execute single block ending with call to quickly get some constant arguments.  I expect that after single step I will be at function start. However if there is CBZ inside block, I can finish somewhere else.

@rhelmot 
Will it be enough to add `strict_basic_block _ends` to `VexControl `, initialize it to `True ` and wrap code in PR https://github.com/angr/vex/pull/10 in conditional statement to check that variable?

If so, I can create new PR.

Thanks.

**Comment by rhelmot** [comment]
That would be fine. You want to make sure that that option can be passed all the way through from pyvex.Block into libVEX, and then add a mechanism in angr to decide which way to set it during analysis.

IMO the best way to set this in angr is with just a global setting in the project (i.e. project.engines.vex) that can be overridden per-lift. We need to make sure there's only one "global default" setting because currently there are two for IR optimization (in the vex engine and a state option) and it's a disaster to make sure you've got the right settings.

**Comment by ArtemShypotilov** [comment]
Hi Audrey,

I have created 2 PRs according to the first part of your comment.

For **VEX**. This one is straightforward. It can work on its own.
https://github.com/angr/vex/pull/15

For **PyVex**. Added variable `strict_block_end` everywhere to lifters and IRSB. Not sure if it is right. Please correct me if I'm wrong. Also please be aware this PR will break` angr/native/sim_unicorn.cpp` as it has call to `vex_lift`.
https://github.com/angr/pyvex/pull/132

For the second part of your comment (_angr_ part) I'm not sure I quite understood you. Below are questions that bother me:

1. What is the uppermost point where I should be able to pass the parameter to angr (or in angr)? Is it option to Project()?
2. I there any similar parameter I can look at? Where is it passed from? Where its default value is specified?

Thanks.

**Comment by rhelmot** [comment]
I merged everything, and implemented the angr interface. see https://github.com/angr/angr/blob/master/tests/test_lifter.py for usage.

There are a handful of testcase failures which are preventing me from switching the option on by default, but if you want this behavior just set `project.engines.vex.default_strict_block_end = True`.

**Comment by honghai0924** [comment]
Hi @rhelmot ,
It seems that the CB{N}Z problem is still there in the newest angr docker image.
`
(angr) angr@62d4322cfc9a:~/angr-dev/angr/tests$ python test_lifter.py
Traceback (most recent call last):
  File "test_lifter.py", line 21, in <module>
    test_strict_block_ends_cbz()
  File "test_lifter.py", line 14, in test_strict_block_ends_cbz
    assert p.factory.block(1, strict_block_end=True).instructions == 2
AssertionError
`
I looked around but couldn't find where the problem is. Could you give me some suggestions?

**Comment by rhelmot** [comment]
Please open a new issue instead of using this two year old one.
