### ISSUE TITLE
Symbolic floating point bug in claripy

### ISSUE THREAD

**Issue by insuyun** [angr/angr#755]
I used same code of [this issue](https://github.com/angr/angr/issues/466)
```c
#include <stdio.h>
#include <stdlib.h>

float fn(float a){
	if(a == 0.1){
		return 0.1;
	}else{
		return 0.0;
	}
}

int main(int argc, char* argv[]){
	fn(4.2);
	return EXIT_SUCCESS;
}
```

I used this script to do symbolic execution on the floating point number.
```python
import angr
import claripy

p = angr.Project("./main", load_options={'auto_load_libs':False})

arg1 = claripy.FPS('arg1', claripy.FSORT_FLOAT)

initial_state = p.factory.call_state(0x4004d6, arg1)
pg = p.factory.simgr(initial_state)

pg.explore(find=0x00000000004004f8)
print(pg)
for pp in pg.deadended:
    print(pp.se.eval(arg1))
```

But unfortunately, I failed to generate the correct input in [the binary](https://drive.google.com/file/d/1yzIqld1Um7KYd9LFuAtqCSArKYJhrepB/view?usp=sharing) that I compiled the code.

The reason that @rhelmot mentioned at the slack is the assembly doesn't check equality, but it checks `arg > 0.1 || arg < 0.1` instead, and the path that represents `arg == 0.1` is marked as unsat by angr somehow.

**Comment by zardus** [comment]
I might be missing something obvious, but you're calling `fn` with a concrete value of `4.2`, so of course it'll never be `== 0.1`?

**Comment by jakkdu** [comment]
If I am correctly understand, the call_state makes a state that executes the function, and the argument is symbolic, so that should be solved.

For example,
if I change the program with interegers,

```c
#include <stdio.h>
#include <stdlib.h>

int fn(int a){
        if(a == 1337){
                return 1;
        }else{
                return 0;
        }
}

int main(int argc, char* argv[]){
        fn(2);
        return EXIT_SUCCESS;
}
```

The code returns 1337.

**Comment by rhelmot** [comment]
(yes, yan, you are missing something obvious, I verified that there's some sort of extremely weird issue)

**Comment by rhelmot** [comment]
So I just verified that this is still an issue. My suspicion is that it is a consequence of https://github.com/angr/angr/issues/785, since replacing `float` with `double` (and changing the data types in the angr script) cause the output to be as expected. The idea here would be that the 0.1 constant we're comparing against is getting mangled by the float-double conversion _inside angr_ and coming up with some values that don't quite work for the arg > 0.1 || arg < 0.1 check.

**Comment by zwimer** [comment]
This should be fixed by https://github.com/angr/claripy/pull/244
